const constants = {
  SELL_CARDS: "SELL_CARDS",
  BUY_CARDS: "BUY_CARDS",
  TRADE_CARDS: "TRADE_CARDS",
  START_GAME: "START_GAME",
  CLEAR_ERROR: "CLEAR_ERROR",
  ADD_ERROR: "ADD_ERROR",
  SET_PLAYER_ID: "SET_PLAYER_ID",
  REMOVE_MARKET_RESOURCE: "REMOVE_MARKET_RESOURCE",
  UPDATE_MARKET_RESOURCE: "UPDATE_MARKET_RESOURCE",
  UPDATE_MARKET_HAND: "UPDATE_MARKET_HAND",
  UPDATE_PLAYER_HAND: "UPDATE_PLAYER_HAND",
  SELECT_MARKET_CARD: "SELECT_MARKET_CARD",
  SELECT_PLAYER_CARD: "SELECT_PLAYER_CARD",
  SET_TURN: "SET_TURN",
  SET_SCORE: "SET_SCORE",
  ADD_MESSAGE: "ADD_MESSAGE",
  CLEAR_MESSAGE: "CLEAR_MESSAGE"
};

export default constants;
