FROM node:8.8
MAINTAINER Flynn Mattson

RUN npm install -g nodemon

WORKDIR /var/www/server
ADD ./server/package.json /var/www/server
RUN npm install

EXPOSE 3001 6379

CMD ["nodemon", "-L", "index.js"]
